name = "hodes-nuxt"
compatibility_date = "2025-10-30"

[vars]
NUXT_PUBLIC_APP_VERSION = "2.1.0"

[env.production.vars]
NUXT_PUBLIC_APP_VERSION = "2.1.0"

[env.preview.vars]
NUXT_PUBLIC_APP_VERSION = "dev-build"